---
framework: mocha
preMerge:
  pattern:
    - "./test/test-python-shell.js"
preRun:
     command:
        - npm ci
        - npm install --save-dev typescript && npx tsc --version && npx tsc -p ./
postMerge:
  pattern: 
    - "./test/test-python-shell.js"
postRun:
     command:
        - node --version
configFile: mocharc.yml
nodeVersion: 10.24.1
version: 1.0
