---
framework: mocha
preMerge:
  pattern:
    - "./test/test-python-shell.js"
preRun:
     command:
        - npm install
        - npm run tsc
        # - npm ci --save-dev typescript && npx tsc --version && npx tsc -p ./
postMerge:
  pattern: 
    - "./test/test-python-shell.js"
postRun:
     command:
        - node --version
configFile: mocharc.yml

nodeVersion: 14.16.1
version: 2.1
